# Configuration related to a specific model.
# For syntax see: https://github.com/toml-lang/toml#table-of-contents


# Model specific common attributes.
[common]

  # Use CUDA for GPU acceleration.
  cuda       = true

  # Batch size for training.
  batch_size = 2

  # Image side size in pixels.
  image_size = 512

  # Directory where to save checkpoints to during training.
  checkpoint = '/tmp/pth/'


# Model specific optimization parameters.
[opt]

  # Total number of epochs to train for.
  epochs     = 10

  # Learning rate for the optimizer.
  lr         = 0.0001

  # Weight decay l2 penalty for the optimizer
  decay      = 0.0001

  # Loss function name (e.g 'Lovasz', 'mIoU' or 'CrossEntropy')
  loss = 'Lovasz'

  # Upscale factor to input image resolution (classical values: 1, 2 or 4) 
  image_upscale = 1
